name: workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-20.04
    steps:
      - name: print
        run: echo "test"
      - name: done
        run: echo "done"
      - name: test
        uses: actions/checkout@v3
      - name: install Node
        uses: actions/setup-node@v3
        with:
          node-verison: 18
      - name: install dependdencies
        run: npm ci
      - name: run tests
        run: npm test
  second-job:
    needs: first-job
    runs-on: macos-14
    steps:
      - name: test2
        run: echo "test2"
